### ISSUE TITLE
As a user, I can build flatpak images from source

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1418]
https://docs.flatpak.org/en/latest/first-build.html

Users will be able to upload a blueprint based on which the image could be built and served afterwards.

**Comment by ipanova** [comment]
`flatpak-builder` does not seem to be a standard container tool. What is the rationale for container registry integration with flatpack builder?

**Comment by lubosmj** [comment]
That was just an idea since we already support building container images in-house. We might use the builder to create an OCI image from a flatpak blueprint and then host it in the Pulp Registry, see https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-build-bundle.

I think we can agree on this not being a priority at the moment.

**Comment by ipanova** [comment]
I see what you mean. That would require a separate build endpoint specifically for building flatpak images because of the underlying builder.  If only builah could do this, I would not be against extending out oci image builder feature to accept some new params like flatpak blueprints, but since this is not the case we should weigh whether this is something we want to generally add to the registry capabilities.
